@hostname = localhost
@port = 3333
@host = {{hostname}}:{{port}}
@contentType = application/json

# @name createEvent
POST http://{{host}}/events
Content-Type: {{contentType}}

{
  "title": "Unite Summit",
  "details": "An event for people that loves programming!",
  "maximumAttendees": 100
}

###

# @name registerForEvent
POST http://{{host}}/events/ac2ecc30-ffbf-4982-a447-f4c66df7de70/attendees
Content-Type: {{contentType}}

{
  "name": "Guilherme Crozariol",
  "email": "guicrozariol@gmail.com"
}